university/academics/urls.py
from django.urls import path
from .views import *
from django.views.generic import TemplateView

app_name="academics"

urlpatterns=[
    path('detail/',display_detail,name="detail"),
    path('course-registration/', course_registration, name='course_registration'),   
    path('edit-detail/',edit_profile,name="edit_detail"),
    path('section/',open_sections,name="sections"),
    # path('teacher/courses/', teacher_courses_view, name='teacher_courses'),

]

university/assessment/urls.py
from django.urls import path
from .quiz_view import *
from .assignment_view import *

app_name='assessment'

urlpatterns =[
    path('create-assignment/<str:teacher_course_id>',create_assignment,name="create_assignment"),
    path('submit-assignment/<str:assignment_id>',submit_assignment , name='submit_assignment'),
    path('teacher-assignment/<str:teacher_course_id>', teacher_view_of_assignments,name='teacher_assignments'),
    path('assignment/<str:course_id>',open_Assignment,name="assignment_view"),
    path('quiz/<str:course_id>',open_Quiz, name="Quiz_view"),
    path('create-quiz/<str:teacher_course_id>/', create_quiz, name='create_quiz'),
    path('add-questions/<str:quiz_id>/', add_questions, name='add_questions'),
    path('take-quiz/<str:quiz_id>/', take_quiz, name='take_quiz'),
    path('quiz-detail/<str:quiz_id>/', quiz_detail, name='quiz_detail'),
    path("edit-assignment/<str:teacher_course_id>/<str:assignment_id>",edit_assignment,name='edit-assignment'),
    path("quiz-result/<str:quiz_id>",quiz_results,name='quiz_results'),
    path("quiz-list/<str:teacher_course_id>",quiz_list,name='quiz_list'),
    path('quiz/<str:quiz_id>/delete/', quiz_delete, name='quiz_delete'),
]

university/university/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django .conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('userauth.urls')),
    path('academics/',include('academics.urls')),
    path('assessment/',include('assessment.urls')),
]
if settings.DEBUG:
    urlpatterns+= static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+= static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

university/userauth/urls.py
from django.urls import path
from .views import *



app_name = "userauth"

urlpatterns =[
    path('',index,name="index"),
    path('sign-out/', logout_view, name="sign-out"),
    path('dashboard/', log_in, name="dashboard"),
    path('sign-in/', signin, name="sign-in"),
    path('sign-up/', signup, name="sign-up"),
]

university/academics/forms.py
from django import forms
from userauth.models import User, Student, Teacher
from academics.models import SemesterYear,AcademicYear,Semester

from .models import SemesterYear

class SemesterYearForm(forms.Form):
    # semester_year = forms.ModelChoiceField(queryset=SemesterYear.objects.all(), label="Select Semester and Academic Year")
    academic_year=forms.ModelChoiceField(queryset=AcademicYear.objects.all(), label="select the Acadamic year")
    semester=forms.ModelChoiceField(queryset=Semester.objects.all(), label="select the semester")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['academic_year'].widget.attrs.update({'class': 'form-control'})
        self.fields['semester'].widget.attrs.update({'class': 'form-control'})

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'gender', 'date_of_birth', 'email', 'profile_picture']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        readonly_fields = ['first_name', 'last_name', 'username', 'date_of_birth']
        for field in readonly_fields:
            self.fields[field].widget.attrs['readonly'] = 'readonly'
        self.fields['gender'].widget.attrs['disabled'] = 'disabled'

        self.fields['profile_picture'].required = False
        self.fields['gender'].widget.attrs['class'] = 'form-control my-custom-class'
        self.fields['first_name'].widget.attrs['class'] = 'form-control my-custom-class'
        self.fields['last_name'].widget.attrs['class'] = 'form-control my-custom-class'
        self.fields['username'].widget.attrs['class'] = 'form-control my-custom-class'
        self.fields['date_of_birth'].widget.attrs['class'] = 'form-control my-custom-class'
        self.fields['email'].widget.attrs['class'] = 'form-control my-custom-class'
        self.fields['profile_picture'].widget.attrs['class'] = 'form-control-file my-custom-class'

    def clean_gender(self):
        # Return the existing gender value to prevent it from being changed
        return self.instance.gender

class StudentDetailsForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ['semester', 'department', 'year', 'section']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        readonly_fields = ['semester', 'department', 'section', 'year']
        for field in readonly_fields:
            self.fields[field].widget.attrs['disabled'] = 'disabled'

        self.fields['semester'].queryset = SemesterYear.objects.all()
        self.fields['semester'].widget.attrs['class'] = 'form-control my-custom-class'
        self.fields['department'].widget.attrs['class'] = 'form-control my-custom-class'
        self.fields['section'].widget.attrs['class'] = 'form-control my-custom-class'
        self.fields['year'].widget.attrs['class'] = 'form-control my-custom-class'

class TeacherDetailsForm(forms.ModelForm):
    class Meta:
        model = Teacher
        fields = ['qualifications', 'department', 'research_interests', 'office_hours']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        readonly_fields = ['qualifications', 'department']
        for field in readonly_fields:
            self.fields[field].widget.attrs['readonly'] = 'readonly'

        self.fields['qualifications'].widget.attrs['class'] = 'form-control my-custom-class'
        self.fields['department'].widget.attrs['class'] = 'form-control my-custom-class'
        self.fields['research_interests'].widget.attrs['class'] = 'form-control my-custom-class'
        self.fields['office_hours'].widget.attrs['class'] = 'form-control my-custom-class'

university/academics/views.py
from django.shortcuts import render, redirect,get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from .models import Enrollment, TeacherCourse,CourseSemesterAvailability,Course
from userauth.models import Student ,User,Teacher
from .forms import *
from django.contrib import messages

@login_required
def display_detail(request):
    user = request.user
    role_name = user.role.role_name if user.role else None

    if role_name == "Student":
        student_profile = get_object_or_404(Student, user=user)
        context = {
            'user_profile': user,
            'profile': student_profile,
        }
        return render(request, "academics/details.html", context)
    elif role_name == "Teacher":
        teacher_profile = get_object_or_404(Teacher, user=user)
        context = {
            'user_profile': user,
            'profile': teacher_profile,
        }
        return render(request, "academics/details.html", context)
    # elif role_name == "Admin":
    #     admin_profile = get_object_or_404(Admin, user=user)
    #     context = {
    #         'user_profile': user,
    #         'profile': admin_profile,
    #     }
    #     return render(request, "academics/admin_details.html", context)
    else:
        return render(request, "academics/unknown_role.html")
    

@login_required
def course_registration(request):
    user = request.user
    student_profile = get_object_or_404(Student, user=user)

    # the student's current semester year is stored in a field `current_semester_year`
    current_semester_year = student_profile.semester
    department = student_profile.department

    if not current_semester_year:
        return HttpResponse("No current semester year found.")

    # Get available courses for the student's current semester year
    available_courses = CourseSemesterAvailability.objects.filter(
        semester_year=current_semester_year, 
        department = department
    )

    enrolled_courses = Enrollment.objects.filter(
        student=student_profile, 
        course_semester__semester_year=current_semester_year
    )
    enrolled_course_ids = enrolled_courses.values_list('course_semester_id', flat=True)
    success = False

    if request.method == 'POST':
        course_semester_ids = request.POST.getlist('course_semester_ids')
        for course_semester_id in course_semester_ids:
            course_semester = CourseSemesterAvailability.objects.get(id=course_semester_id)

            # Create an enrollment if not already enrolled
            if not Enrollment.objects.filter(student=student_profile, course_semester=course_semester).exists():
                Enrollment.objects.create(student=student_profile, course_semester=course_semester)

        success = True

    context = {
        'user_profile': user,
        'profile': student_profile,
        'available_courses': available_courses, 
        'enrolled_course_ids': enrolled_course_ids,
        'success': success,
    }

    return render(request, 'academics/course_registration.html', context)

@login_required
def edit_profile(request):
    user = request.user
    user_form = UserProfileForm(instance=user)
    student_form = None
    teacher_form = None

    if request.method == 'POST':
        user_form = UserProfileForm(request.POST, request.FILES, instance=user)
        if user.role.role_name == "Student":
            student_profile = get_object_or_404(Student, user=user)
            student_form = StudentDetailsForm(request.POST, instance=student_profile)

            for field in ['first_name', 'last_name', 'username', 'date_of_birth']:
                user_form.fields[field].disabled = True
            
            for field in ['semester', 'department', 'section','year']:
                student_form.fields[field].disabled = True

            if user_form.is_valid():
                user_form.save()
                if student_form.is_valid():
                    
                    # Retain the original gender and profile picture if not provided
                    student_profile = student_form.save(commit=False)
                    # student_profile.gender = user.gender
                    if 'profile_picture' in request.FILES:
                        user.profile_picture = request.FILES['profile_picture']
                    else:
                        user.profile_picture = user_form.initial['profile_picture']
                    student_profile.save()
                    messages.success(request, 'Profile updated successfully.')
                    return redirect('academics:detail')
                else:
                    print(student_form.errors)
            else:
                # print(teacher_form.errors)
                messages.error(request, 'Please correct the errors below.')
        
        elif user.role.role_name == "Teacher":
            teacher_profile = get_object_or_404(Teacher, user=user)
            teacher_form = TeacherDetailsForm(request.POST, instance=teacher_profile)

            for field in ['first_name', 'last_name', 'username', 'date_of_birth','gender']:
                user_form.fields[field].disabled = True
            
            for field in ['qualifications', 'department','office_hours' ]:
                teacher_form.fields[field].disabled = True

            if user_form.is_valid():
                
                user_form.save()
                if teacher_form.is_valid():
                    teacher_profile = teacher_form.save(commit=False)
                    # teacher_profile.gender = user.gender
                    if 'profile_picture' in request.FILES:
                        user.profile_picture = request.FILES['profile_picture']
                    else:
                        user.profile_picture = user_form.initial['profile_picture']
                    teacher_profile.save()
              
                    messages.success(request, 'Profile updated successfully.')
                   
                    return redirect('academics:detail')
                else:
                    print(teacher_form.errors)
            else:
                messages.error(request, 'Please correct the errors below.')
    else:
        if user.role.role_name == "Student":
            student_profile = get_object_or_404(Student, user=user)
            student_form = StudentDetailsForm(instance=student_profile)
        

        elif user.role.role_name == "Teacher":
            teacher_profile = get_object_or_404(Teacher, user=user)
            teacher_form = TeacherDetailsForm(instance=teacher_profile)
        

    context = {
        'user_form': user_form,
        'student_form': student_form,
        'teacher_form': teacher_form,
    }

    return render(request, 'academics/edit_detail.html', context)

@login_required
def open_sections(reqeust):
    return render(reqeust,'academics/teacher_sections.html')
    

university/templates/academics/course_registration.html
{% extends "parents/parent.html" %}
{% load static %}
{% block content %}

<div class="page-wrapper">
  <div class="content container-fluid">
     <div class="page-header">
        <div class="row align-items-center">
           <div class="col">
              <h3 class="page-title">Courses</h3>
              <ul class="breadcrumb">
                 <li class="breadcrumb-item"><a href="#">Dashboard</a></li>
                 <li class="breadcrumb-item active">Course Registration</li>
              </ul>
           </div>
        </div>
     </div>

        <div class="col-sm-12">
          <div class="card card-table">
            <div class="card-body">
              <div class="table-responsive">
                <form method="post">
                  {% csrf_token %}
                  <table class="table table-hover table-center mb-0 datatable">
                    <thead>
                      <tr>
                        <th>CourseID</th>
                        <th>CourseName</th>
                        <th>Credit</th>
                        <th class="text-right">
                          Register  <input type="checkbox" id="select_all" onclick="toggleSelectAll(this)"> 
                        </th>
                      </tr>
                    </thead>
                    <tbody>
                      {% for course_offering in available_courses %}
                        <tr>
                          <td>{{ course_offering.course.course_code }}</td>
                          <td>
                            <h2><a>{{ course_offering.course.course_name }}</a></h2>
                          </td>
                          <td>{{ course_offering.course.credit_hours }}</td>
                          <td class="text-right">
                            <div class="actions">
                              {% if course_offering.id in enrolled_course_ids %}
                                <span class="badge badge-success">Already Registered</span>
                              {% else %}
                                <input type="checkbox" name="course_semester_ids" value="{{ course_offering.id }}" class="course_checkbox" id="course_{{ course_offering.id }}">
                              {% endif %}
                            </div>
                          </td>
                        </tr>
                      {% endfor %}
                    </tbody>
                    
                  </table>
                  <div class="text-right mt-3">
                    <button type="submit" class="btn btn-primary">Register</button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
  </div>
</div>

<!-- Success Modal -->
<div class="modal fade" id="successModal" tabindex="-1" aria-labelledby="successModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="successModalLabel">Registration Successful</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        You have successfully registered for the following courses:
        <table class="table table-hover table-center mb-0 datatable">
          <thead>
            <tr>
              <th>CourseID</th>
              <th>CourseName</th>
              <th>Credit</th>
            </tr>
          </thead>
          <tbody>
            {% for course_offering in available_courses %}
              <tr>
                <td>{{ course_offering.course.course_code }}</td>
                <td>
                  <h2><a>{{ course_offering.course.course_name }}</a></h2>
                </td>
                <td>{{ course_offering.course.credit_hours }}</td>
              </tr>
            {% endfor %}
          </tbody>
          
        </table>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
      <div class="modal-footer">
        <button class="btn"><i class="fa fa-download"></i> Download</button>
      </div>
    </div>
  </div>
</div>

<script>
  function toggleSelectAll(selectAllCheckbox) {
    const checkboxes = document.querySelectorAll('.course_checkbox');
    checkboxes.forEach((checkbox) => {
      checkbox.checked = selectAllCheckbox.checked;
    });
  }

  document.addEventListener('DOMContentLoaded', function() {
    var success = "{{ success }}";
    if (success === "True") {
      $('#successModal').modal('show');
    }
  });
</script>

{% endblock %}

university/templates/academics/teacher_sections.html
{% extends "parents/parent.html" %}
{% load static %}
{% block content %}
<div class="page-wrapper">
    <div class="content container-fluid">
        <div class="page-header">
            <div class="row align-items-center">
                <div class="col">
                    <div class="container-fluid">
                        <div class="course-item1 ">
                            <h3>{{ user_profile.first_name }} {{user_profile.last_name }}'s Sections</h3>
                            <p>Academic Year: <span>{{current_academic_year_and_semester}}</span></p>
                            <h6>Academic Semester: <span>{{current_academic_year_and_semester.academic_Semester}}</span></h6>

                        </div> 
                        <br>

                        {% if teacher_courses %}
                            <div class="course-list">
                                <div class="course-item1">
                                        <div>Section</div>
                                        <div>Department</div>
                                        <div>Course ID</div>                                       
                                        <div>Course Name</div>
                                        <div>Credit</div>
                                        <div>Remark</div>
                                </div>
                                {% for teacher_course in teacher_courses %}
                                    <div class="course-item clickable-row" data-index="{{ forloop.counter }}">
                                        <div class="course-section">{{ teacher_course.section.section_name }}</div>
                                        <div class="course-department">{{ teacher_course.section.department.department_name }}</div>
                                        <div class="course-id">{{ teacher_course.course_semester.course.course_code }}</div>
                                        <div class="course-name">{{ teacher_course.course_semester.course.course_name }}</div>
                                        <div class="course-credit">{{ teacher_course.course_semester.course.credit_hours }}</div>
                                        <div class="course-remark"><a href="javascript:void(0);">Details</a></div>
                                    </div>
                                    <div id="details-{{ forloop.counter }}" class="details-row collapse">
                                        <div class="dropdown-content">
                                            <a class="dropdown-item" href="{% url 'assessment:create_assignment' teacher_course.teacher_course_id %}">Create Assignments</a>
                                            <a class="dropdown-item" href="{% url 'assessment:teacher_assignments' teacher_course.teacher_course_id %}">Check Submited Assignments</a>
                                            <a class="dropdown-item" href="{% url 'assessment:create_quiz' teacher_course.teacher_course_id %} ">Quizzes</a>
                                            <a class="dropdown-item" href="{% url 'assessment:quiz_list' teacher_course.teacher_course_id %} ">Quizzes List</a>
                                            <!-- <a class="dropdown-item" href="#">Quizzes</a> -->
                                            <a class="dropdown-item" href="#">Materials</a>
                                            <a class="dropdown-item" href="#">Grades</a>
                                        </div>
                                    </div>
                                {% endfor %}
                            </div>
                        {% else %}
                            <div class="alert alert-info mt-3" role="alert">
                                You are not teaching any courses in {{ semester_year }}.
                            </div>
                        {% endif %}
                        
                        <div class="card-body">
                            {% if message %}
                                <div class="alert alert-info mt-3" role="alert">
                                    {{ message }}
                                </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<style>
    /* .page-wrapper{
        background-color: #867c7c;

    } */
    .course-list {
        margin-top: 20px;
    }
    .course-item {
        display: flex;
        justify-content: space-between;
        padding: 15px;
        border-radius: 5px;
        margin-bottom: 10px;
        background-color: #ffffff;
        border:solid  #f9f9f9;
    }
    .course-item1{
        display: flex;
        justify-content: space-between;
        padding: 15px;
        border-radius: 5px;
        margin-bottom: 10px;
        background-color: #635f5f;
        border:solid  #f9f9f9;
        color: white;

    }
    .course-item:hover{
        font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;
        color:  #007bff;
        font-weight: bolder;
        transform: scale(1.06);
    }
    .course-item div {
        flex: 1;
        padding: 0 10px;
    }
    .course-item1 div{
        flex: 1;
        padding: 0 10px;
    }
    .details-row {
        display: none;
    }
    .details-row.show {
        display: block;
        /* border: 1px solid #696868; */
        margin-bottom: 10px;
    }
    .clickable-row {
        cursor: pointer;
    }
    .dropdown-content {
        background-color: #f9f9f9;
        /* border: 1px solid #ccc; */
        padding: 10px 20px;
    }
    .dropdown-item {
        padding: 10px 15px;
        display: block;
        text-decoration: none;
        color: #333;
        /* border-bottom: 1px solid #ddd; */
    }
    .dropdown-item:last-child {
        border-bottom: none;
    }
    .dropdown-item:hover {
        background-color: #ffffff;
        color: #007bff;
        transform: scale(1.1);
    }
</style>

<script>
    document.addEventListener("DOMContentLoaded", function() {
        var clickableRows = document.querySelectorAll(".clickable-row");
        clickableRows.forEach(function(row) {
            row.addEventListener("click", function() {
                var index = row.getAttribute("data-index");
                var detailsRow = document.querySelector("#details-" + index);
                var isShown = detailsRow.classList.contains("show");

                document.querySelectorAll(".details-row").forEach(function(element) {
                    element.classList.remove("show");
                });

                if (!isShown) {
                    detailsRow.classList.add("show");
                }
            });
        });
    });
</script>

{% endblock %}