university/assessment/urls.py
from django.urls import path
from .quiz_view import *
from .assignment_view import *

app_name='assessment'

urlpatterns =[
    path('create-assignment/<str:teacher_course_id>',create_assignment,name="create_assignment"),
    path('submit-assignment/<str:assignment_id>',submit_assignment , name='submit_assignment'),
    path('teacher-assignment/<str:teacher_course_id>', teacher_view_of_assignments,name='teacher_assignments'),
    path('assignment/<str:course_id>',open_Assignment,name="assignment_view"),
    path('quiz/<str:course_id>',open_Quiz, name="Quiz_view"),
    path('create-quiz/<str:teacher_course_id>/', create_quiz, name='create_quiz'),
    path('add-questions/<str:quiz_id>/', add_questions, name='add_questions'),
    path('take-quiz/<str:quiz_id>/', take_quiz, name='take_quiz'),
    path('quiz-detail/<str:quiz_id>/', quiz_detail, name='quiz_detail'),
    path("edit-assignment/<str:teacher_course_id>/<str:assignment_id>",edit_assignment,name='edit-assignment'),
    path("quiz-result/<str:quiz_id>",quiz_results,name='quiz_results'),
    path("quiz-list/<str:teacher_course_id>",quiz_list,name='quiz_list'),
    path('quiz/<str:quiz_id>/delete/', quiz_delete, name='quiz_delete'),
]

university/university/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django .conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('userauth.urls')),
    path('academics/',include('academics.urls')),
    path('assessment/',include('assessment.urls')),
]
if settings.DEBUG:
    urlpatterns+= static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+= static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

university/userauth/urls.py
from django.urls import path
from .views import *



app_name = "userauth"

urlpatterns =[
    path('',index,name="index"),
    path('sign-out/', logout_view, name="sign-out"),
    path('dashboard/', log_in, name="dashboard"),
    path('sign-in/', signin, name="sign-in"),
    path('sign-up/', signup, name="sign-up"),
]

university/userauth/models.py
from django.db import models
from shortuuid.django_fields import ShortUUIDField
from django.utils.html import mark_safe
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import post_save
from django.dispatch import receiver

class Role(models.Model):


    role_id = ShortUUIDField(unique=True, length=5, max_length=10, prefix="Role", alphabet="1234567890")
    role_name = models.CharField(max_length=100)
    def __str__(self):
        return self.role_name

    class Meta:
        verbose_name = "Role"
        verbose_name_plural = "Roles"

class User(AbstractUser):
    user_id = ShortUUIDField(unique=True, length=10, max_length=20, prefix="User", alphabet="1234567890", primary_key=True)
    email = models.EmailField(max_length=255, unique=True)
    username = models.CharField(max_length=100, unique=True)
    role = models.ForeignKey(Role, on_delete=models.SET_NULL, null=True, blank=True)
    date_of_birth = models.DateField(null=True, blank=True)
    address = models.CharField(max_length=255, null=True, blank=True)
    phone = models.CharField(max_length=20, null=True, blank=True)
    gender = models.CharField(max_length=10, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], null=True, blank=True)
    profile_picture = models.ImageField(upload_to='profile_pictures/', null=True, blank=True)
    account_status = models.CharField(max_length=20, default='Active')
    last_login = models.DateTimeField(null=True, blank=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    def __str__(self):
        return self.username
    class Meta:
        verbose_name = "User"
        verbose_name_plural = "Users"


@receiver(post_save, sender=User)
def create_related_profile(sender, instance, created, **kwargs):
    if created:
        if instance.role:
            if instance.role.role_name == 'Student':
                Student.objects.create(user=instance)
            elif instance.role.role_name == 'Teacher':
                Teacher.objects.create(user=instance)
                


class Teacher(models.Model):
    teacher_id = ShortUUIDField(
        length=7, 
        prefix='tea', 
        primary_key=True,
        alphabet="1234567890"
    )
    user = models.OneToOneField(User, on_delete=models.CASCADE,editable=False)
    qualifications = models.TextField(null=True, blank=True)
    # experience = models.PositiveIntegerField()
    office_hours = models.CharField(max_length=255, null=True, blank=True)
    research_interests = models.TextField(null=True, blank=True)
    department = models.ForeignKey('academics.Department', on_delete=models.SET_NULL, null=True,related_name='Teacher')

    def __str__(self):
        return f"Teacher: {self.user.username}"

    class Meta:
        verbose_name = "Teacher"
        verbose_name_plural = "Teachers"

class Student(models.Model):
    student_id = ShortUUIDField(
         length=7, 
         prefix='stu', 
         primary_key=True,alphabet="1234567890"
    )    
    user = models.OneToOneField(User, on_delete=models.CASCADE,editable=False)
    section=models.ForeignKey('academics.Section',on_delete=models.SET_NULL,null=True)
    year=models.ForeignKey('academics.year',on_delete=models.SET_NULL,null=True)
    semester=models.ForeignKey('academics.SemesterYear',on_delete=models.SET_NULL,null=True)
    department = models.ForeignKey('academics.Department', on_delete=models.SET_NULL, null=True)
    

    def __str__(self):
        return f"Student: {self.user.username}"

    class Meta:
        verbose_name = "Student"
        verbose_name_plural = "Students"
        

university/userauth/views.py
from django.conf import settings
from django.contrib.auth import authenticate, login,logout
from django.shortcuts import render, redirect,get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import User, Student, Teacher
from academics.models import Enrollment
from django.contrib import messages

user = settings.AUTH_USER_MODEL

@login_required
def index(request):
    return render(request,"userauth/index.html")

def signin(request):
    return render(request,"userauth/sign_in.html")

def signup(request):
    return render(request,"userauth/sign_up.html")

def logout_view(request):
    logout(request)
    return redirect("userauth:sign-in")

def log_in(request):
    if request.user.is_authenticated: 
        return render(request, 'userauth/index.html')
    
    elif request.method == "POST":
        email = request.POST.get('email')
        password = request.POST.get('password')
        remember_me = request.POST.get('remember_me')
        
        if not email or not password:
            messages.error(request, 'Email and password are required.')
            return render(request, 'userauth/sign_in.html')

        try:
            user = User.objects.get(email=email)
        except User.DoesNotExist:
            messages.error(request, 'The email address is not registered.')
            return render(request, 'userauth/sign_in.html')

        if not user.check_password(password):
            messages.error(request, 'Incorrect password.')
            return render(request, 'userauth/sign_in.html')

        if not user.is_active:
            messages.error(request, 'This account is inactive.')
            return render(request, 'userauth/sign_in.html')

        user = authenticate(request, email=email, password=password)
        if user is not None:
            login(request, user)
            if remember_me:
                request.session.set_expiry(60 * 60 * 24 * 30)  # 30 days
            else:
                request.session.set_expiry(0)  # Browser session
            
            # Redirect to the same function to handle the authenticated user case
            return redirect('userauth:dashboard')
        else:
            messages.error(request, 'Invalid email or password.')
            return render(request, 'userauth/sign_in.html')
    
    return render(request, 'userauth/sign_in.html')

university/templates/userauth/index.html
{% extends "parents/parent.html" %}
{% load static %}

{% block content %}

<div class="page-wrapper">
<div class="content container-fluid">

<div class="page-header">
    <div class="row">
        <div class="col-sm-12">
        <h3 class="page-title">Welcome {{user_profile.first_name}} {{ user_profile.last_name}}!</h3>
            <ul class="breadcrumb">
                <li class="breadcrumb-item"><a href="index.html">Dashboard</a></li>
                <li class="breadcrumb-item active">{{user_profile.role}} </li>
            </ul>
        </div>
    </div>
</div>


<div class="row">
    {% for i in current_courses %}
    <div class="col-xl-3 col-sm-6 col-12 d-flex">
        <div class="card bg-nine w-100">
            <a href="#">
            <div class="card-body">
                <div class="db-widgets d-flex justify-content-between align-items-center">
                    <div class="db-icon">
                        <i class="fas fa-book-open"></i>
                        
                    </div>
                     
                        <div class="db-info">
                        <!-- <h5><a href="{% url 'assessment:assignment_view' i.course_id %}">Assignment</a></h5>
                        <h5> <a href="{% url 'assessment:Quiz_view' i.course_id %}">Quiz</a></h5> -->
                        <h6>{{i.course_name}}</h6>
                        <h6>{{i.course_code}}</h6>
                    </div>
                
                </div>
            </div>
            </a>
        </div>
    </div>
    {% endfor %}
    <!-- <div class="col-xl-3 col-sm-6 col-12 d-flex">
        <div class="card bg-six w-100">
            <div class="card-body">
                <div class="db-widgets d-flex justify-content-between align-items-center">
                    <div class="db-icon">
                    <i class="fas fa-file-alt"></i>
                    </div>
                    <div class="db-info">
                    <h3>40/60</h3>
                    <h6>{{current_courses}}</h6>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xl-3 col-sm-6 col-12 d-flex">
        <div class="card bg-six w-100">
            <div class="card-body">
                <div class="db-widgets d-flex justify-content-between align-items-center">
                    <div class="db-icon">
                    <i class="fas fa-file-alt"></i>
                    </div>
                    <div class="db-info">
                    <h3>40/60</h3>
                    <h6>{{current_courses}}</h6>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xl-3 col-sm-6 col-12 d-flex">
        <div class="card bg-six w-100">
            <div class="card-body">
                <div class="db-widgets d-flex justify-content-between align-items-center">
                    <div class="db-icon">
                    <i class="fas fa-file-alt"></i>
                    </div>
                    <div class="db-info">
                    <h3>40/60</h3>
                    <h6>{{current_courses}}</h6>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div> -->
<div class="row">
<div class="col-12 col-lg-12 col-xl-9">
<div class="card flex-fill">
    <div class="card-header">
        <div class="row align-items-center">
            <div class="col-6">
            <h5 class="card-title">Upcoming Quizs and Assignments </h5>
            </div>
            <div class="col-6">
            <span class="float-right view-link"><a href="#">what is this?</a></span>
            </div>
        </div>
    </div>
<div class="dash-circle">
<div class="row">
<div class="col-12 col-lg-6 col-xl-6 dash-widget3">
    <div class="card-body dash-widget1">
    <div class="circle-bar circle-bar2">
        <div class="circle-graph2" data-percent="20">
            <b>20%</b>
            </div>
            <h6>Completed</h6>
            <h4>1 <span>/ 5</span></h4>
    </div>
    <div class="dash-details">
    <h4> Upcoming Assignments</h4>
            <ul>
                <li><i class="fas fa-clock"></i> Java</li>
                <li><i class="fas fa-book-open"></i> Monday</li>
                <li><i class="fas fa-hourglass-end"></i> 2:30 pm -3:00 pm</li>
                <li><i class="fas fa-clipboard-check"></i> countdown </li>
            </ul>
        <div class="dash-btn">
            <button type="submit" class="btn btn-info btn-border">Skip</button>
            <button type="submit" class="btn btn-info">Continue</button>
        </div>
    </div>
    </div>
</div>
<div class="col-12 col-lg-6 col-xl-6 dash-widget3">
    <div class="card-body dash-widget1">
    <div class="circle-bar circle-bar2">
        <div class="circle-graph2" data-percent="20">
            <b>20%</b>
            </div>
            <h6>Completed</h6>
            <h4>1 <span>/ 5</span></h4>
    </div>
    <div class="dash-details">
    <h4>Upcoming Quizs</h4>
            <ul>
                    <li><i class="fas fa-clock"></i> Java</li>
                    <li><i class="fas fa-book-open"></i> Monday</li>
                    <li><i class="fas fa-hourglass-end"></i> 2:30 pm -3:00 pm</li>
                    <li><i class="fas fa-clipboard-check"></i> countdown </li>
            </ul>
        <div class="dash-btn">
            <button type="submit" class="btn btn-info btn-border">See More</button>
            <button type="submit" class="btn btn-info">Continue</button>
        </div>
    </div>
    </div>
</div>
</div>
</div>
</div>
<div class="row">

<div class="col-12 col-lg-12 col-xl-4 d-flex">
    <div class="card flex-fill">
        <div class="card-header">
            <h5 class="card-title">Learning History</h5>
        </div>
        <div class="card-body">
            <div class="teaching-card">
                <ul class="activity-feed">
                    <li class="feed-item">
                        <div class="feed-date1">Sep 05, 9 am - 10 am (60min)</div>
                        <span class="feed-text1"><a>course 1 </a></span>
                        <p><span>In Progress</span></p>
                    </li>
                    <li class="feed-item">
                        <div class="feed-date1">Sep 05, 9 am - 10 am (60min)</div>
                        <span class="feed-text1"><a>course 1 </a></span>
                        <p><span>In Progress</span></p>
                    </li>
                    <li class="feed-item">
                        <div class="feed-date1">Sep 05, 9 am - 10 am (60min)</div>
                        <span class="feed-text1"><a>course 1 </a></span>
                        <p><span>In Progress</span></p>
                    </li>
                    <li class="feed-item">
                        <div class="feed-date1">Sep 05, 9 am - 10 am (60min)</div>
                        <span class="feed-text1"><a>course 1 </a></span>
                        <p><span>In Progress</span></p>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
</div>
</div>


</div>

</div>


{% endblock %}

university/templates/userauth/sign_in.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
   <!-- Mirrored from preschool.dreamguystech.com/html-template/login.html by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 28 Oct 2021 11:11:39 GMT -->
   <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0">
      <title>Preskool - Login</title>
      <link rel="shortcut icon" href="assets/img/download_small.jpeg">
      <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,500;0,600;0,700;1,400&amp;display=swap">
      <link rel="stylesheet" href="{% static 'assets/plugins/bootstrap/css/bootstrap.min.css' %}">
      <link rel="stylesheet" href="{% static 'assets/plugins/fontawesome/css/fontawesome.min.css' %}">
      <link rel="stylesheet" href="{% static 'assets/plugins/fontawesome/css/all.min.css' %}">
      <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
   </head>
   <body>
    <div class="header">

        <div class="header-left">
        <a href="index.html" class="logo">
          <img src="{% static 'assets/img/downloads.png' %}" alt="Logo">
        </a>
        <a href="index.html" class="logo logo-small">
           <img src="{% static 'assets/img/download_small.jpeg' %}" alt="Logo" width="30" height="30">
        </a>
        </div>
    
        <a href="javascript:void(0);" id="toggle_btn">
           <i class="fas fa-align-left"></i>
        </a>
    
        <div class="top-nav-search">
        <form>
        <input type="text" class="form-control" placeholder="Search here">
        <button class="btn" type="submit"><i class="fas fa-search"></i></button>
        </form>
        </div>
    
    
        <a class="mobile_btn" id="mobile_btn">
           <i class="fas fa-bars"></i>
        </a>
    </div>
      <div class="main-wrapper login-body">
         <div class="login-wrapper">
            <div class="container">
               <div class="loginbox">
                  <div class="login-left">
                     <img class="img-fluid" src="{% static 'assets/img/downloads.png' %}" alt="Logo">
                  </div>
                  <div class="login-right">
                     <div class="login-right-wrap">
                        
                        <h1>Login</h1>
                        <p class="account-subtitle">Access to our dashboard</p>
                        <form action="{% url 'userauth:dashboard' %}", method="POST">
                            {% csrf_token %}
                           <div class="form-group">
                              <input class="form-control" type="email" id="email" name="email" placeholder="Email" required>
                           </div>
                           <div class="form-group">
                              <input class= "form-control" type="password" id="password" name="password" placeholder="Password" required>                           </div>
                           <div class="form-group">
                              <button class="btn btn-primary btn-block" type="submit">Login</button>
                           </div>
                        </form>
                        <!-- <div class="card-body"> -->
                           {% if messages %}
                              <div class="alert alert-danger">
                                 {% for message in messages %}
                                       <p>{{ message }}</p>
                                 {% endfor %}
                              </div>
                           {% endif %}
                         <!-- </div> -->
                        <div class="text-center forgotpass"><a href="forgot-password.html">Forgot Password?</a></div>
                        <div class="login-or">
                           <span class="or-line"></span>
                           <span class="span-or">or</span>
                        </div>
                        <div class="social-login">
                           <span>Login with</span>
                           <a href="#" class="facebook"><i class="fab fa-facebook-f"></i></a><a href="#" class="google"><i class="fab fa-google"></i></a>
                        </div>
                        <div class="text-center dont-have">Don’t have an account? <a href="{% url 'userauth:sign-up' %}">Register</a></div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
      <script src="{% static 'assets/js/jquery-3.6.0.min.js' %}"></script>
      <script src="{% static 'assets/js/popper.min.js' %}"></script>
      <script src="{% static 'assets/plugins/bootstrap/js/bootstrap.min.js' %}"></script>
      <script src="{% static 'assets/js/script.js' %}"></script>
   </body>
   <!-- Mirrored from preschool.dreamguystech.com/html-template/login.html by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 28 Oct 2021 11:11:40 GMT -->
</html>

university/templates/userauth/sign_up.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<!-- Mirrored from preschool.dreamguystech.com/html-template/register.html by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 28 Oct 2021 11:11:58 GMT -->
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0">
<title>Preskool - Register</title>

<link rel="shortcut icon" href="{% static 'assets/img/download_small.jpeg' %}">
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,500;0,600;0,700;1,400&amp;display=swap">

<link rel="stylesheet" href="{% static 'assets/plugins/bootstrap/css/bootstrap.min.css' %}">

<link rel="stylesheet" href="{% static 'assets/plugins/fontawesome/css/fontawesome.min.css' %}">
<link rel="stylesheet" href="{% static 'assets/plugins/fontawesome/css/all.min.css' %}">

<link rel="stylesheet" href="{%  static 'assets/css/style.css' %}">
</head>
<body>
    <div class="header">

        <div class="header-left">
        <a href="index.html" class="logo">
          <img src="{% static 'assets/img/downloads.png' %}" alt="Logo">
        </a>
        <a href="index.html" class="logo logo-small">
           <img src="{% static 'assets/img/download_small.jpeg' %}" alt="Logo" width="30" height="30">
        </a>
        </div>
    
        <a href="javascript:void(0);" id="toggle_btn">
           <i class="fas fa-align-left"></i>
        </a>
    
        <div class="top-nav-search">
        <form>
        <input type="text" class="form-control" placeholder="Search here">
        <button class="btn" type="submit"><i class="fas fa-search"></i></button>
        </form>
        </div>
    
    
        <a class="mobile_btn" id="mobile_btn">
           <i class="fas fa-bars"></i>
        </a>
    
    
        <!-- <ul class="nav user-menu">
    
            <li class="nav-item dropdown noti-dropdown">
                <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
                     <i class="far fa-bell"></i> <span class="badge badge-pill">3</span>
                </a>
                <div class="dropdown-menu notifications">
                    <div class="topnav-dropdown-header">
                      <span class="notification-title">Notifications</span>
                          <a href="javascript:void(0)" class="clear-noti"> Clear All </a>
                     </div>
                <div class="noti-content">
                    <ul class="notification-list">
                       <li class="notification-message">
                       <a href="#">
                          <div class="media">
                            <span class="avatar avatar-sm">
                            <img class="avatar-img rounded-circle" alt="User Image" src="{% static 'assets/img/profiles/avatar-02.jpg' %}">
                            </span>
                            <div class="media-body">
                                <p class="noti-details"><span class="noti-title">Mercury Software Inc</span> added a new product <span class="noti-title">Apple MacBook Pro</span></p>
                                <p class="noti-time"><span class="notification-time">12 mins ago</span></p>
                                </div>
                          </div>
                        </a>
                        </li>
                    </ul>
                </div>
                <div class="topnav-dropdown-footer">
                      <a href="#">View all Notifications</a>
                </div>
                </div>
            </li>
    
            
            
    
        </ul> -->
    
        </div>
<div class="main-wrapper login-body">
<div class="login-wrapper">
    <div class="container">
        <div class="loginbox">
            <div class="login-left">
                <img class="img-fluid" src="{% static 'assets/img/downloads.png' %}" alt="Logo">
            </div>
            <div class="login-right">
                <div class="login-right-wrap">
                <h1>Register</h1>
                <p class="account-subtitle">Access to our dashboard</p>

                <form action="https://preschool.dreamguystech.com/html-template/login.html">
                    <div class="form-group">
                    <input class="form-control" type="text" placeholder="Name">
                    </div>
                    <div class="form-group">
                    <input class="form-control" type="text" placeholder="Email">
                    </div>
                    <div class="form-group">
                    <input class="form-control" type="text" placeholder="Password">
                    </div>
                    <div class="form-group">
                    <input class="form-control" type="text" placeholder="Confirm Password">
                    </div>
                    <div class="form-group mb-0">
                    <button class="btn btn-primary btn-block" type="submit">Register</button>
                    </div>
                </form>

                <div class="login-or">
                <span class="or-line"></span>
                <span class="span-or">or</span>
                </div>

                <div class="social-login">
                <span>Register with</span>
                <a href="#" class="facebook"><i class="fab fa-facebook-f"></i></a><a href="#" class="google"><i class="fab fa-google"></i></a>
                </div>

                <div class="text-center dont-have">Already have an account? <a href="{% url 'userauth:sign-in' %}">Login</a></div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
<footer>
    <p>Copyright © 2020 Dreamguys.</p>
    </footer>

<script src="{% static 'assets/js/jquery-3.6.0.min.js' %}"></script>

<script src="{% static 'assets/js/popper.min.js' %}"></script>
<script src="{% static 'assets/plugins/bootstrap/js/bootstrap.min.js' %}"></script>

<script src="{% static 'assets/js/script.js' %}"></script>
</body>

<!-- Mirrored from preschool.dreamguystech.com/html-template/register.html by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 28 Oct 2021 11:11:58 GMT -->
</html>